const FIND_TICKETS_TYPES = {
  /** tickets */
  TICKETS: {
    ADD: 'FIND_TICKETS.TICKETS.ADD',
    IS_FETCHING: 'FIND_TICKETS.TICKETS.IS_FETCHING',
    IS_ERROR: 'FIND_TICKETS.TICKETS.IS_ERROR',
  },

  /** filters */
  FILTERS: {
    TRANSFERS: {
      TOGGLE_ALL: 'FIND_TICKETS.FILTERS.TRANSFERS.TOGGLE_ALL',
      TOGGLE_OPTION: 'FIND_TICKETS.FILTERS.TRANSFERS.TOGGLE_OPTION',
    }
  },

  /** sort */
  SORT: {
    BY: 'FIND_TICKETS.SORT.BY',
  },
}

const ACTION_TYPES = {
  FIND_TICKETS: FIND_TICKETS_TYPES
}

export default ACTION_TYPES
